ARCHS = armv7 armv7s arm64
include $(THEOS)/makefiles/common.mk

TOOL_NAME = playcli
playcli_FILES = main.mm
playcli_FRAMEWORKS = AVFoundation AudioToolbox
playcli_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tool.mk
